### ISSUE TITLE
support for 'describe' and 'test'

### ISSUE THREAD

**Issue by adam-pog** [elixir-editors/language-elixir#106]
While 'describe' and 'test' are ExUnit macros, I noticed you already have snippet support for them. Are you planning on adding them to the grammar to support highlighting / would you accept a PR for it?

**Comment by keathley** [comment]
I think this would be reasonable. What are you expecting to see them highlighted as?

**Comment by adam-pog** [comment]
I would expect them to highlight the same as `def`, `defmodule`, `if`, etc. They seem to fit the same role as other 'control' keywords that encapsulate some related section of code.

**Comment by keathley** [comment]
I think that could make sense. My only argument against this is that test and describe are really just macros. They're provided by ExUnit but otherwise they aren't really that special. Given that we don't highlight any other macros in this way I'm not sure it makes sense to do it here. That being said I don't feel super strongly about it. What do you think about that reasoning @adam-pog?

**Comment by adam-pog** [comment]
@keathley Yeah that makes sense, and I also don't feel very strongly about it. I know many other testing frameworks have their own packages, but wasn't sure if ExUnit would be treated differently since it ships with elixir. I figured i'd check here first before going out of my way to make a specific 'language-exunit' package.

**Comment by keathley** [comment]
I believe that the vim and emacs packages include the support for `describe` and `test` so I guess the precedent has already been set. We should probably support this as well.

**Comment by keathley** [comment]
This has been published.
